from __future__ import annotations

from cloudshell.cp.core.request_actions import DeployVMRequestActions
from cloudshell.cp.core.request_actions.models import DeployApp

from cloudshell.cp.proxmox import constants
from cloudshell.cp.proxmox.models.base_deployment_app import (
    ResourceAttrRODeploymentPath,
    ResourceBoolAttrRODeploymentPath,
    ResourceIntAttrRODeploymentPath,
    ProxmoxDeploymentAppAttributeNames,
    ProxmoxCloneModeAttrRO,
    ProxmoxInstanceFromVMDeploymentAppAttributeNames,
    ProxmoxInstanceFromTemplateDeploymentAppAttributeNames,
    ProxmoxInstanceFromQEMUImageDeploymentAppAttributeNames,
    ProxmoxInstanceFromContainerImageDeploymentAppAttributeNames,
    ProxmoxInstanceFromContainerDeploymentAppAttributeNames,
)


class BaseProxmoxDeployApp(DeployApp):
    _DO_NOT_EDIT_APP_NAME = True
    ATTR_NAMES = ProxmoxDeploymentAppAttributeNames

    target_node = ResourceAttrRODeploymentPath(ATTR_NAMES.target_node)
    target_storage = ResourceAttrRODeploymentPath(ATTR_NAMES.target_storage)
    behavior_during_save = ResourceAttrRODeploymentPath(ATTR_NAMES.behavior_during_save)
    auto_power_on = ResourceBoolAttrRODeploymentPath(ATTR_NAMES.auto_power_on)
    auto_power_off = ResourceBoolAttrRODeploymentPath(ATTR_NAMES.auto_power_off)
    ip_regex = ResourceAttrRODeploymentPath(ATTR_NAMES.ip_regex)
    wait_for_ip = ResourceBoolAttrRODeploymentPath(ATTR_NAMES.wait_for_ip)
    auto_delete = ResourceBoolAttrRODeploymentPath(ATTR_NAMES.auto_delete)
    autoload = ResourceBoolAttrRODeploymentPath(ATTR_NAMES.autoload)
    refresh_ip_timeout = ResourceIntAttrRODeploymentPath(ATTR_NAMES.refresh_ip_timeout)
    autogenerated_name = ResourceBoolAttrRODeploymentPath(ATTR_NAMES.autogenerated_name)


class InstanceFromVMDeployApp(BaseProxmoxDeployApp):
    ATTR_NAMES = ProxmoxInstanceFromVMDeploymentAppAttributeNames

    DEPLOYMENT_PATH = constants.VM_FROM_VM_DEPLOYMENT_PATH
    vm_id = ResourceAttrRODeploymentPath(ATTR_NAMES.vm_id)
    sm_snapshot = ResourceAttrRODeploymentPath(ATTR_NAMES.snapshot)


class InstanceFromTemplateDeployApp(BaseProxmoxDeployApp):
    ATTR_NAMES = ProxmoxInstanceFromTemplateDeploymentAppAttributeNames

    DEPLOYMENT_PATH = constants.VM_FROM_TEMPLATE_DEPLOYMENT_PATH
    template_id = ResourceAttrRODeploymentPath(ATTR_NAMES.template_id)
    clone_mode = ProxmoxCloneModeAttrRO(ATTR_NAMES.clone_mode)


class InstanceFromQEMUImageDeployApp(BaseProxmoxDeployApp):
    ATTR_NAMES = ProxmoxInstanceFromQEMUImageDeploymentAppAttributeNames

    DEPLOYMENT_PATH = constants.VM_FROM_QEMU_DEPLOYMENT_PATH
    image_url = ResourceAttrRODeploymentPath(ATTR_NAMES.image_url)


class InstanceFromContainerImageDeployApp(BaseProxmoxDeployApp):
    ATTR_NAMES = ProxmoxInstanceFromContainerImageDeploymentAppAttributeNames

    DEPLOYMENT_PATH = constants.CONTAINER_FROM_IMAGE_DEPLOYMENT_PATH
    container_image = ResourceAttrRODeploymentPath(ATTR_NAMES.container_image)


class InstanceFromContainerApp(BaseProxmoxDeployApp):
    ATTR_NAMES = ProxmoxInstanceFromContainerDeploymentAppAttributeNames

    DEPLOYMENT_PATH = constants.CONTAINER_FROM_IMAGE_DEPLOYMENT_PATH
    container_id = ResourceAttrRODeploymentPath(ATTR_NAMES.container_id)


class ProxmoxDeployVMRequestActions(DeployVMRequestActions):
    deploy_app: BaseProxmoxDeployApp
