from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from attrs import define

from cloudshell.cp.proxmox.handlers.proxmox_handler import ProxmoxHandler

if TYPE_CHECKING:
    from cloudshell.cp.proxmox.models.deployed_app import BaseProxmoxDeployedApp
    from cloudshell.cp.proxmox.resource_config import ProxmoxResourceConfig

logger = logging.getLogger(__name__)


@define
class ProxmoxDeleteFlow:
    _si: ProxmoxHandler
    _deployed_app: BaseProxmoxDeployedApp
    _resource_config: ProxmoxResourceConfig

    def _get_expected_vm_name(self) -> str | None:
        deployed_app = self._deployed_app
        candidate_names = [
            getattr(deployed_app, "vmName", None),
            getattr(deployed_app, "vm_name", None),
        ]

        vmdetails = getattr(deployed_app, "vmdetails", None)
        if vmdetails:
            candidate_names.extend(
                [
                    getattr(vmdetails, "vmName", None),
                    getattr(vmdetails, "name", None),
                ]
            )

        additional_data = getattr(deployed_app, "deployedAppAdditionalData", None)
        if isinstance(additional_data, dict):
            candidate_names.extend(
                [
                    additional_data.get("proxmox_vm_name"),
                    additional_data.get("vmName"),
                ]
            )

        autogenerated_name = getattr(deployed_app, "autogenerated_name", None)
        deployed_resource_name = getattr(deployed_app, "name", None)
        if autogenerated_name is False and deployed_resource_name:
            candidate_names.append(deployed_resource_name.replace(" ", "-"))

        for candidate_name in candidate_names:
            if isinstance(candidate_name, str) and candidate_name.strip():
                return candidate_name

        return None

    def delete(self) -> None:
        """Power ON Virtual Machine."""
        instance_id = int(self._deployed_app.vmdetails.uid)
        expected_vm_name = self._get_expected_vm_name()
        logger.info(
            "Powering Off and Deleting the %s with expected Proxmox name %s",
            self._deployed_app.vmdetails.uid,
            expected_vm_name,
        )
        self._si.delete_instance_if_name_matches(
            instance_id=instance_id, expected_name=expected_vm_name
        )
