from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from attrs import define

from cloudshell.cp.proxmox.flows.deploy_flow.base_flow import PROXMOX_VM_NAME_PARAM
from cloudshell.cp.proxmox.handlers.proxmox_handler import ProxmoxHandler

if TYPE_CHECKING:
    from cloudshell.cp.proxmox.models.deployed_app import BaseProxmoxDeployedApp
    from cloudshell.cp.proxmox.resource_config import ProxmoxResourceConfig

logger = logging.getLogger(__name__)


@define
class ProxmoxDeleteFlow:
    _si: ProxmoxHandler
    _deployed_app: BaseProxmoxDeployedApp
    _resource_config: ProxmoxResourceConfig

    def _get_expected_vm_name(self) -> str | None:
        deployed_app = self._deployed_app

        # This is the only channel that actually survives from Deploy to Delete:
        # cloudshell-cp-core reconstructs deployed_app fresh on every call from
        # CloudShell's stored resource data, and it only carries over `attributes`,
        # `name` and `vmdetails` (incl. `vm_custom_params`, set from the VM Details
        # properties pushed at deploy time). Neither `vmName`/`vm_name` nor
        # `deployedAppAdditionalData` exist on that reconstructed object, so reading
        # them here always returns None - see base_flow.py's PROXMOX_VM_NAME_PARAM.
        vmdetails = getattr(deployed_app, "vmdetails", None)
        vm_custom_params = getattr(vmdetails, "vm_custom_params", None) or {}
        if isinstance(vm_custom_params, dict):
            name = vm_custom_params.get(PROXMOX_VM_NAME_PARAM)
            if isinstance(name, str) and name.strip():
                return name

        # Fallback for VMs deployed before this param existed, or if the platform
        # ever drops custom params: only valid when the Proxmox name wasn't
        # randomized, i.e. it's exactly the CloudShell resource name.
        autogenerated_name = getattr(deployed_app, "autogenerated_name", None)
        deployed_resource_name = getattr(deployed_app, "name", None)
        if autogenerated_name is False and deployed_resource_name:
            return deployed_resource_name.replace(" ", "-")

        return None

    def delete(self) -> None:
        """Power ON Virtual Machine."""
        instance_id = int(self._deployed_app.vmdetails.uid)
        expected_vm_name = self._get_expected_vm_name()
        logger.info(
            "Powering Off and Deleting the %s with expected Proxmox name %s",
            self._deployed_app.vmdetails.uid,
            expected_vm_name,
        )
        self._si.delete_instance_if_name_matches(
            instance_id=instance_id, expected_name=expected_vm_name
        )
